---
title: "6_visualising_valence"
author: "Sebastian Ploner"
output:
  html_document:
    code_folding: show
    df_print option: paged
    highlight: pygments
    toc: no
    toc_depth: 3
  pdf_document: default
  word_document:
    toc: yes
    toc_depth: '3'
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE) # echo = FALSE for hiden code

```


```{r Load libraries, import data and adjust variable classes}

library("tidyverse")
library("plotly")


# set new working directory
file_path = "/Users/sebastian/Documents/Uni/Sheffield (MSc)/2. Semester/Data Analysis and Viz/spotify_audio_feature_analysis/"
setwd(file_path)

library("here") # set working directory PRIOR to loading "here".

data = read.csv(here("data", "6_predicted_valence.csv")) # week as character such that the leading zero is not lost as it is important for further analysis and visualisation in particular

# converting variables to the right type
data$country = as.factor(data$country)
data$date = as.Date(data$date)

knitr::kable(head(data))

```


```{r Smoothing valence}

# smoothing the proportion of deviation
models = data %>%
  tidyr::nest(-country) %>%
  dplyr::mutate(
    # Perform loess calculation on each country
    m = purrr::map(data, loess,
                   formula = proportion_of_deviation ~ as.numeric(date), span = 0.2),
    # Retrieve the fitted values from each model
    fitted = purrr::map(m, `[[`, "fitted"))


# apply fitted y's as a new column
results = models %>%
  dplyr::select(-m) %>%
  tidyr::unnest()

```


```{r Valence heat map, fig.width = 12, fig.height = 10}

# ordering countries loosely by proximity
level_ordered = c("Global", "New Zealand", "Australia", "Philippines", "Hong Kong SAR China", "Japan", "Singapore", "Malaysia", "Vietnam", "Thailand", "Taiwan", "Indonesia", "Israel", "Turkey", "Greece", "Cyprus", "Bulgaria", "Hungary", "Czechia", "Romania", "Poland", "Slovakia", "Austria","Luxembourg", "Switzerland", "Italy", "Germany", "Netherlands", "Belgium", "France", "Spain", "Portugal", "United Kingdom", "Ireland", "Denmark", "Norway", "Sweden", "Finland", "Latvia", "Lithuania", "Estonia", "South Africa", "Iceland", "United States", "Canada", "Mexico", "Dominican Republic", "Guatemala", "El Salvador", "Honduras", "Nicaragua", "Costa Rica", "Panama", "Colombia", "Ecuador", "Peru", "Bolivia", "Chile", "Brazil", "Paraguay", "Argentina", "Uruguay")

results$country = factor(results$country, levels = level_ordered)


# heat map for smoothed data
valence_heatmap = results %>%
  filter(country != "Cyprus", date < "2021-02-05") %>%
  ggplot(aes(date, country, fill = fitted)) +
  geom_tile(color="white") +
  
  scale_fill_gradientn(colours = c("#971D2B", "#FDFDC3", "#2B653C"),
                       values = c(0, 0.5, 1),
                       limits = c(-0.27, 0.27),
                       labels = scales::percent_format(accuracy = 1L),
                       name = "Deviation from\nexpected valence",
                       guide = guide_legend(
                         direction = "horizontal",
                         title.position = "top",
                         label.position = "bottom")) +
  
  scale_x_date(date_breaks = "2 month",
               date_labels = "%b %Y",
               expand = c(0,0),
               sec.axis = dup_axis()) +
  scale_y_discrete(limits = rev) +
  
  labs(title = "Valence got low, low, low, low, low, low, low, low",
       subtitle = "Based on Spotify's weekly top 200 songs per country",
       caption = "", x = "", y = "") +
  
  theme_classic() +
  
  theme(plot.title = element_text(size = 18, face = "bold"),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.margin = margin(1, 1.5, 0, 0.5, "cm"),
        legend.position = "top",
        legend.justification = "right",
        legend.title.align = 1,
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(1, "cm"),
        legend.spacing.x = unit(0, "cm"),
        legend.margin = margin(t = - 1.3, unit = "cm"),
        legend.box.margin = margin(0, 0, -0.5, 0, unit = "cm"))

valence_heatmap
# ggsave("figures/valence_heatmap.png", valence_heatmap, width = 15, height = 13)

# valence_heatmap_html = ggplotly(valence_heatmap)
# valence_heatmap_html

```


```{r Valence line plot, fig.width = 10}

# line plot
valence_line_plot = data %>%
  filter(country == "United States" | country == "United Kingdom" | country == "Germany") %>% 
  
  ggplot(aes(date, proportion_of_deviation, colour = country)) + geom_line() +
  
  theme_classic() +
  theme(panel.grid.major = element_line(size = 0.1, colour = "gray"),
        plot.title = element_text(size = 18, face = "bold")) +
  
  scale_x_date(name = "", date_breaks = "2 month", date_labels = "%b %Y") +
  scale_y_continuous(name = "Deviation from expected valence",
                     labels = scales::percent_format(accuracy = 1L),
                     limits = c(-0.25, 0.25)) +
  scale_colour_discrete(name = "Country") +
  
  labs(title = "Valence during Covid-19 times",
       subtitle = "Based on Spotify's weekly top 200 songs")

valence_line_plot

# ggsave("figures/valence.png", test2, width = 10, height = 6)

```

